version: "3.2"

services:
  db:
    image: postgres:14
    restart: always
    container_name: todo-app-db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    container_name: todo-app-app
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on:
      - db
    network_mode: host
